routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-session', function() {
    session()->forget('username');
    // return back();
});

Route::get('/','frontend\HomeController@index')->name('index');
Route::get('search','frontend\HomeController@search')->name('search');
//                         LOGIN                 //
Route::resource('login','frontend\LoginController');  //frontend
Route::post('logout','frontend\LoginController@logout')->name('logout');//frontend
Route::get('/admin/login','backend\HomeController@loginAdmin')->name('admin.login'); //backend
Route::post('process-login','backend\HomeController@processLogin')->name('process.login'); //backend
Route::post('admin-logout','backend\HomeController@logout')->name('admin.logout');//backend
///////////////////////////////////////////////////////////////////////////////////////////////////////
                //          frontend         //
Route::resource('user','frontend\UserController');
Route::get('/order-create','backend\OrderController@create')->name('order-create');
Route::post('/orders-store','backend\OrderController@store')->name('orders-store');
Route::get('/contactus','frontend\HomeController@contactus')->name('contactus');
Route::get('/detail','frontend\HomeController@detail')->name('detail');
Route::get('/checkout','frontend\HomeController@checkout')->name('checkout');
Route::get('/aboutus','frontend\HomeController@aboutus')->name('aboutus');
Route::get('/comic','frontend\HomeController@comic')->name('comic');
Route::get('/stationery','frontend\HomeController@stationery')->name('stationery');
Route::get('/magazine','frontend\HomeController@magazine')->name('magazine');
Route::get('/promotion','frontend\HomeController@promotion')->name('promotion');
Route::get('/book','frontend\HomeController@book')->name('book');
Route::get('/Faq','frontend\HomeController@Faq')->name('Faq');
Route::get('/my-account','frontend\MyAccountController@MyAccount')->name('my-account');
Route::get('/purchase','frontend\MyAccountController@purchase')->name('purchase');
Route::resource('product-img','backend\ProductImgController');
Route::resource('product-cmt','backend\ProductCmtController'); 
Route::resource('customer','frontend\UserController');
Route::get('/blog','frontend\HomeController@blog')->name('blog');
Route::get('/history','frontend\HomeController@history')->name('history');
Route::get('/history-detail/{id}','frontend\HomeController@histotyDeitail')->name('history-detail');
Route::resource('contact','frontend\ContactController');
//                       cart                       //
Route::get('/cart','frontend\CartController@cart')->name('cart');
Route::post('/add-cart','frontend\CartController@addcart')->name('add.cart');
Route::post('/delete-cart-item', 'frontend\CartController@deleteCartItem')->name('delete-cart-item');
Route::post('/delete-cart', 'frontend\CartController@deleteCart')->name('delete-cart');
Route::post('/chang-cart-quantity', 'frontend\CartController@changCartQuantity')->name('chang-cart-quantity');
/////////////////////////////////////////////////////////////////////////////////////////////////////
                 //          backend             //       
Route::group(['prefix' => 'admin',  'middleware' => 'admin'], function() {
    Route::get('/','backend\HomeController@dashboard')->name('dashboard');
    Route::get('/accountAdmin','backend\HomeController@adminIndex')->name('accountAdmin');
    Route::resource('account','backend\UserController');
    Route::resource('config','backend\ConfigController');
    Route::resource('sliders','backend\SliderController');
    Route::resource('product','backend\ProductController');
    Route::resource('orders','backend\OrderController');
    Route::resource('order-detail','backend\OrderDetailController');
    Route::get('order/{id}','backend\OrderController@orderDetail')->name('detail');
    Route::get('/detail-customer/{id}','backend\HomeController@detailCustomer')->name('detail-customer');
    Route::get('/detail/{id}','backend\HomeController@OrderDetail')->name('detail-order');
    Route::resource('blogadmin','backend\BlogController');
    Route::get('/contact','backend\HomeController@contact')->name('contact');
});
Route::get('{any}-{id}','frontend\HomeController@productDetails')->name('product-details');

resources/views/admin/dashboard.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
<section class="content">
    <div class="container-fluid">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-info">
            <div class="inner">
              <h3>{{ $order ?? ''}}</h3>

              <p>New Orders</p>
            </div>
            <div class="icon">
              <i class="ion ion-bag"></i>
            </div>
            <a href="{{ route('orders.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
          <!-- small box -->
          <div class="small-box bg-success">
            <div class="inner">
              <h3>{{ $product ?? ''}}</h3>

              <p>Product</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            <a href="{{ route('product.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-3 col-6">
          <div class="small-box bg-danger">
            <div class="inner">
              <h3> ${{ number_format($total_sale ??'') }}</h3>
              <p>Total income</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <p class="small-box-footer" style="text-align: left; padding-left:10px">Total book: {{ $qty ?? '' }}</p>
          </div>
        </div>
        <div class="col-lg-3 col-6">
          <!-- small box -->  
          <div class="small-box bg-warning">
            <div class="inner">
              <h3>{{ $user ?? ''}}</h3>

              <p>User Registrations</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{{route('account.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/loginAdmin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{{ asset('dist/css/login.css') }}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>Login Admin Book</title>
</head>
<body class="body">
    
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    ADMIN BOOK 
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form action="{{route('process.login')}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-controll" name="username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-controll" name="password">
                            </div>

                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>





</body>
</html>