routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-session', function() {
    session()->forget('username');
    // return back();
});

Route::get('/','frontend\HomeController@index')->name('index');
Route::get('search','frontend\HomeController@search')->name('search');
//                         LOGIN                 //
Route::resource('login','frontend\LoginController');  //frontend
Route::post('logout','frontend\LoginController@logout')->name('logout');//frontend
Route::get('/admin/login','backend\HomeController@loginAdmin')->name('admin.login'); //backend
Route::post('process-login','backend\HomeController@processLogin')->name('process.login'); //backend
Route::post('admin-logout','backend\HomeController@logout')->name('admin.logout');//backend
///////////////////////////////////////////////////////////////////////////////////////////////////////
                //          frontend         //
Route::resource('user','frontend\UserController');
Route::get('/order-create','backend\OrderController@create')->name('order-create');
Route::post('/orders-store','backend\OrderController@store')->name('orders-store');
Route::get('/contactus','frontend\HomeController@contactus')->name('contactus');
Route::get('/detail','frontend\HomeController@detail')->name('detail');
Route::get('/checkout','frontend\HomeController@checkout')->name('checkout');
Route::get('/aboutus','frontend\HomeController@aboutus')->name('aboutus');
Route::get('/comic','frontend\HomeController@comic')->name('comic');
Route::get('/stationery','frontend\HomeController@stationery')->name('stationery');
Route::get('/magazine','frontend\HomeController@magazine')->name('magazine');
Route::get('/promotion','frontend\HomeController@promotion')->name('promotion');
Route::get('/book','frontend\HomeController@book')->name('book');
Route::get('/Faq','frontend\HomeController@Faq')->name('Faq');
Route::get('/my-account','frontend\MyAccountController@MyAccount')->name('my-account');
Route::get('/purchase','frontend\MyAccountController@purchase')->name('purchase');
Route::resource('product-img','backend\ProductImgController');
Route::resource('product-cmt','backend\ProductCmtController'); 
Route::resource('customer','frontend\UserController');
Route::get('/blog','frontend\HomeController@blog')->name('blog');
Route::get('/history','frontend\HomeController@history')->name('history');
Route::get('/history-detail/{id}','frontend\HomeController@histotyDeitail')->name('history-detail');
Route::resource('contact','frontend\ContactController');
//                       cart                       //
Route::get('/cart','frontend\CartController@cart')->name('cart');
Route::post('/add-cart','frontend\CartController@addcart')->name('add.cart');
Route::post('/delete-cart-item', 'frontend\CartController@deleteCartItem')->name('delete-cart-item');
Route::post('/delete-cart', 'frontend\CartController@deleteCart')->name('delete-cart');
Route::post('/chang-cart-quantity', 'frontend\CartController@changCartQuantity')->name('chang-cart-quantity');
/////////////////////////////////////////////////////////////////////////////////////////////////////
                 //          backend             //       
Route::group(['prefix' => 'admin',  'middleware' => 'admin'], function() {
    Route::get('/','backend\HomeController@dashboard')->name('dashboard');
    Route::get('/accountAdmin','backend\HomeController@adminIndex')->name('accountAdmin');
    Route::resource('account','backend\UserController');
    Route::resource('config','backend\ConfigController');
    Route::resource('sliders','backend\SliderController');
    Route::resource('product','backend\ProductController');
    Route::resource('orders','backend\OrderController');
    Route::resource('order-detail','backend\OrderDetailController');
    Route::get('order/{id}','backend\OrderController@orderDetail')->name('detail');
    Route::get('/detail-customer/{id}','backend\HomeController@detailCustomer')->name('detail-customer');
    Route::get('/detail/{id}','backend\HomeController@OrderDetail')->name('detail-order');
    Route::resource('blogadmin','backend\BlogController');
    Route::get('/contact','backend\HomeController@contact')->name('contact');
});
Route::get('{any}-{id}','frontend\HomeController@productDetails')->name('product-details');

app/Models/Config.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Config extends Model
{
    use HasFactory;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'webname',
        'logo',
        'hotline',
        'facebook',
        'zalo',
        'address',
        'email',
    ];
}

app/Http/Controllers/backend/ConfigController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Models\Config;
use App\Models\Orders;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class ConfigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $order = Orders::all()->count('id');
        $config = Config::all();
        $title = 'Admin | Config';
        return view('admin.config.index',['title' => $title], compact('config','order'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $order = Orders::all()->count('id');
        return view('admin.config.config',compact('order'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $config = $request->all();
        if ($request->hasFile('logo')) {
            $file = $request->file('logo');
            $extension = $file->getClientOriginalExtension();            
            if ($extension != 'jpg' && $extension != 'jpeg' && $extension != 'png') {
                return redirect()->route('config.config');
            }
            
            $imgName = $file->getClientOriginalName();
            $file->move('images', $imgName);
            $config['logo'] = $imgName;
        }
        Config::create($config);
        return redirect()->route('config.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function show(Config $config)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $config = Config::find($id);
        $title = 'Admin | Edit Config';
        $order = Orders::all()->count('id');
        return view('admin.config.update',['title' => $title], compact('order','config'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $config = Config::find($id);
        $config->webname = $request->input('webname');
        if ($request->hasFile('logo')) {
            $file = $request->file('logo');
            $extension = $file->getClientOriginalExtension();            
            if ($extension != 'jpg' && $extension != 'jpeg' && $extension != 'png') {
                return redirect()->route('config.config');
            }
            $imgName = $file->getClientOriginalName();
            $file->move('images', $imgName);
            $config['logo'] = $imgName;
        }
        $config->hotline = $request->input('hotline');
        $config->facebook = $request->input('facebook');
        $config->zalo = $request->input('zalo');
        $config->address = $request->input('address');
        $config->email = $request->input('email');
        $config->save();
        Session::flash('message', "Successfully deleted");
        return redirect()->route('config.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Config  $config
     * @return \Illuminate\Http\Response
     */
    public function destroy(Config $config)
    {
        if ($config->logo != null) {
            if (file_exists('images/' . $config->logo)) {
                unlink('images/' . $config->logo);
            }
        }
        $config->delete();
        return redirect()->route('config.index');
    }
}

resources/views/admin/config/config.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <section class="content">
        <form action="{{ route('config.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Dislpay Website</h3>
                    </div>
                        <div class="card-body row">
                            <div class="form-group col-md-6">
                                <label for="inputName">Website Name</label>
                                <input type="text" id="inputClientCompany" name="webname" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="image">Logo</label>
                                <input type="file" id="image" name="logo" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Hotline</label>
                                <input type="text" id="inputClientCompany" name="hotline" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Facebook</label>
                                <input type="text" id="inputClientCompany" name="facebook" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Zalo</label>
                                <input type="text" id="inputClientCompany" name="zalo" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Address</label>
                                <input type="text" id="inputClientCompany" name="address" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Email</label>
                                <input type="email" id="inputClientCompany" name="email" required class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="#" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Create" class="btn btn-success float-right">
                </div>
            </div>
        </form>
    </section>
@endsection

resources/views/admin/config/index.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Config Web</h3>
  
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 3%" class="text-center">
                          Id
                      </th>
                      <th style="width: 10%" class="text-center">
                          Web Name
                      </th>
                      <th style="width: 10%" class="text-center">
                          Logo
                      </th>
                      <th style="width: 10%" class="text-center">
                          Facebook
                      </th>
                      <th style="width: 10%" class="text-center">
                          Zalo
                      </th>
                      <th style="width: 10%" class="text-center">
                          Address
                      </th>
                      <th style="width: 10%" class="text-center">
                        Email
                      </th>
                      <th style="width: 10%" class="text-center">
                        Actions
                      </th>
                  </tr>
              </thead>
              <tbody>
                @foreach ($config as $item)
                  <tr>
                    <td class="text-center">
                        {{ $item->id }}
                    </td>
                    <td class="text-center">
                        {{ $item->webname }}
                    </td>
                    @if ( $item->logo != null)
                        <td class="text-center">
                            <img src="{{ asset('/images/' . $item->logo) }}" alt="{{ $item->logo }}" style="width: 100px; height: auto" >
                        </td>
                    @endif
                    <td class="text-center">
                        {{ $item->facebook }}
                    </td>
                    <td class="text-center">
                        {{ $item->zalo }}
                    </td>
                    <td class="text-center">
                        {{ $item->address }}
                    </td>
                    <td class="text-center">
                        {{ $item->email }}
                    </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-info btn-sm" href="{{ route('config.edit', $item->id) }}">
                              <i class="fas fa-pencil-alt">
                              </i>
                          </a>
                          <form style="display:inline-block" action="{{ route('config.destroy', $item->id) }}" method="POST">
                            @method("DELETE")
                            @csrf
                            <button class="btn btn-danger"><i class="fas fa-trash"></i></button>
                          </form>
                      </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

resources/views/admin/config/update.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <section class="content">
        <form action="{{ route('config.update',$config->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="_method" value="PUT">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Dislpay Website</h3>
                    </div>
                        <div class="card-body row">
                            <div class="form-group col-md-6">
                                <label for="inputName">Website Name</label>
                                <input type="text" id="inputClientCompany" name="webname" value="{{ $config->webname }}" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="image">Logo</label>
                                <input type="file" id="image" name="logo" value="{{ $config->logo }}" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Hotline</label>
                                <input type="text" id="inputClientCompany" name="hotline" value="{{ $config->hotline }}" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Facebook</label>
                                <input type="text" id="inputClientCompany" name="facebook" value="{{ $config->facebook }}" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Zalo</label>
                                <input type="text" id="inputClientCompany" name="zalo" value="{{ $config->zalo }}" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Address</label>
                                <input type="text" id="inputClientCompany" name="address" value="{{ $config->address }}" required class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputClientCompany">Email</label>
                                <input type="email" id="inputClientCompany" name="email" value="{{ $config->email }}" required class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{{ route('config.index') }}" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Update" class="btn btn-success float-right">
                </div>
            </div>
        </form>
    </section>
@endsection