routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-session', function() {
    session()->forget('username');
    // return back();
});

Route::get('/','frontend\HomeController@index')->name('index');
Route::get('search','frontend\HomeController@search')->name('search');
//                         LOGIN                 //
Route::resource('login','frontend\LoginController');  //frontend
Route::post('logout','frontend\LoginController@logout')->name('logout');//frontend
Route::get('/admin/login','backend\HomeController@loginAdmin')->name('admin.login'); //backend
Route::post('process-login','backend\HomeController@processLogin')->name('process.login'); //backend
Route::post('admin-logout','backend\HomeController@logout')->name('admin.logout');//backend
///////////////////////////////////////////////////////////////////////////////////////////////////////
                //          frontend         //
Route::resource('user','frontend\UserController');
Route::get('/order-create','backend\OrderController@create')->name('order-create');
Route::post('/orders-store','backend\OrderController@store')->name('orders-store');
Route::get('/contactus','frontend\HomeController@contactus')->name('contactus');
Route::get('/detail','frontend\HomeController@detail')->name('detail');
Route::get('/checkout','frontend\HomeController@checkout')->name('checkout');
Route::get('/aboutus','frontend\HomeController@aboutus')->name('aboutus');
Route::get('/comic','frontend\HomeController@comic')->name('comic');
Route::get('/stationery','frontend\HomeController@stationery')->name('stationery');
Route::get('/magazine','frontend\HomeController@magazine')->name('magazine');
Route::get('/promotion','frontend\HomeController@promotion')->name('promotion');
Route::get('/book','frontend\HomeController@book')->name('book');
Route::get('/Faq','frontend\HomeController@Faq')->name('Faq');
Route::get('/my-account','frontend\MyAccountController@MyAccount')->name('my-account');
Route::get('/purchase','frontend\MyAccountController@purchase')->name('purchase');
Route::resource('product-img','backend\ProductImgController');
Route::resource('product-cmt','backend\ProductCmtController'); 
Route::resource('customer','frontend\UserController');
Route::get('/blog','frontend\HomeController@blog')->name('blog');
Route::get('/history','frontend\HomeController@history')->name('history');
Route::get('/history-detail/{id}','frontend\HomeController@histotyDeitail')->name('history-detail');
Route::resource('contact','frontend\ContactController');
//                       cart                       //
Route::get('/cart','frontend\CartController@cart')->name('cart');
Route::post('/add-cart','frontend\CartController@addcart')->name('add.cart');
Route::post('/delete-cart-item', 'frontend\CartController@deleteCartItem')->name('delete-cart-item');
Route::post('/delete-cart', 'frontend\CartController@deleteCart')->name('delete-cart');
Route::post('/chang-cart-quantity', 'frontend\CartController@changCartQuantity')->name('chang-cart-quantity');
/////////////////////////////////////////////////////////////////////////////////////////////////////
                 //          backend             //       
Route::group(['prefix' => 'admin',  'middleware' => 'admin'], function() {
    Route::get('/','backend\HomeController@dashboard')->name('dashboard');
    Route::get('/accountAdmin','backend\HomeController@adminIndex')->name('accountAdmin');
    Route::resource('account','backend\UserController');
    Route::resource('config','backend\ConfigController');
    Route::resource('sliders','backend\SliderController');
    Route::resource('product','backend\ProductController');
    Route::resource('orders','backend\OrderController');
    Route::resource('order-detail','backend\OrderDetailController');
    Route::get('order/{id}','backend\OrderController@orderDetail')->name('detail');
    Route::get('/detail-customer/{id}','backend\HomeController@detailCustomer')->name('detail-customer');
    Route::get('/detail/{id}','backend\HomeController@OrderDetail')->name('detail-order');
    Route::resource('blogadmin','backend\BlogController');
    Route::get('/contact','backend\HomeController@contact')->name('contact');
});
Route::get('{any}-{id}','frontend\HomeController@productDetails')->name('product-details');

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    use HasFactory;
    protected $fillable = [
        'category_id',
        'name',
        'author',
        'price',
        'price_sale',
        'description',
        'pub_company',
        'date_publishing',
        'publisher',
        'status',
        'url',
        'image_1',
        'image_2',
    ];
    public function Product_image(){
        return $this->hasMany(Product_image::class , 'product_id');
    }
    public function Product_cmt(){
        return $this->hasMany(Product_comment::class , 'product_id');
    }
}

app/Http/Controllers/backend/ProductController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Config;
use App\Models\Order_detail;
use App\Models\Orders;
use App\Models\Products;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $config = Config::all();
        $orders = Order_detail::where('product_id','!=','0');
        // $products = Products::all()->sortByDesc('id');
        $products = DB::table('Products')->select("products.*",DB::raw('(CASE WHEN order_details.id IS NOT NULL THEN "0" ELSE 1 END) AS delete_id'))
                                        ->leftJoin('order_details','products.id','=','order_details.product_id')
                                        ->orderBy('products.id','desc')->groupBy('products.id')->get();
        $order = Orders::all()->count('id');
        $title = 'Book Store | Products';
        return view('admin.product.index',['title' => $title],compact('products','order','orders','config'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $config = Config::all();
        $categorys =  Category::all();
        $title = 'Book Store | Create Products';
        $order = Orders::all()->count('id');
        return view('admin.product.add-product.add-product',['title' => $title], compact('categorys','order','config'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $products = $request->all();
        // kiểm tra file có tồn tại hay không?
        if ($request->hasFile('image_1')) {
            $file = $request->file('image_1');
            // lấy phần mở rộng (extension) của file để kiểm tra xem 
            // đây có phải là file hình
            $extension = $file->getClientOriginalExtension();            
            if ($extension != 'jpg' && $extension != 'jpeg' && $extension != 'png') {
                return redirect()->route('product.add-product');
            }
            
            $imgName = $file->getClientOriginalName();
            // copy file vào thư mục public/images
            $file->move('products', $imgName);
            // tạo phần tử image trong mảng $product
            $products['image_1'] = $imgName;
        }
        Products::create($products);
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function show(Products $products)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $config = Config::all();
        $categorys =  Category::all();
        $products = Products::find($id);
        $title = 'Book Store | Edit Products';
        return view('admin.product.update-product.update-product',['title' => $title],compact('products','categorys','config'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $products = Products::find($id);
        $products->category_id = $request->input('category_id');
        $products->name = $request->input('name');
        $products->author = $request->input('author');
        $products->price = $request->input('price');
        $products->price_sale = $request->input('price_sale');
        $products->description = $request->input('description');
        $products->pub_company = $request->input('pub_company');
        $products->date_publishing = $request->input('date_publishing');
        $products->publisher = $request->input('publisher');
        $products->status = $request->input('status');
        $products->url = $request->input('url');
        if ($request->hasFile('image_1')) {
            $file = $request->file('image_1');
            // lấy phần mở rộng (extension) của file để kiểm tra xem 
            // đây có phải là file hình
            $extension = $file->getClientOriginalExtension();            
            if ($extension != 'jpg' && $extension != 'jpeg' && $extension != 'png') {
                return redirect()->route('product.add-product');
            }
            
            $imgName = $file->getClientOriginalName();
            // copy file vào thư mục public/images
            $file->move('products', $imgName);
            // tạo phần tử image trong mảng $product
            $products['image_1'] = $imgName;
        }
        $products->save();
        Session::flash('message', "Successfully deleted");
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function destroy(Products $products,$id)
    {   
        $products = Products::find($id);
        if ($products->image_1 != null) {
            if (file_exists('products/' . $products->image_1)) {
                unlink('products/' . $products->image_1);
            }
        }
        $products->delete();
        return redirect()->route('product.index');
    }
}

resources/views/admin/product/index.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
          <h3 class="card-title"> Product</h3>
          <div class="card-tools row">
            <div class="col-md-5" style="width: 100px">
              <a href="{{ route('product.create') }}">Create</a>
            </div>
            <button type="button" class="btn btn-tool col-md-2" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool col-md-2" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 2%" class="text-center">
                          Id
                      </th>
                      <th style="width: 10%" class="text-center">
                        Name
                      </th>
                      <th style="width: 3%" class="text-center">
                          Price
                      </th>
                      <th style="width: 5%" class="text-center">
                          Price Sale
                      </th>
                      <th style="width: 8%" class="text-center">
                        Image
                      </th>
                      <th style="width: 0%" class="text-center">
                        Actions
                      </th>
                  </tr>
              </thead>
              <tbody>
                @foreach ($products as $item)
                  <tr>
                    <td class="text-center" style="font-size: 14px">
                      {{ $item->id }}
                    </td>
                    <td class="text-center" style="font-size: 14px">
                        {{ $item->name }}
                    </td>
                    <td class="text-center" style="font-size: 14px">
                      <del> ${{ number_format($item->price) }} </del>
                    </td>
                    <td class="text-center" style="font-size: 14px">
                      ${{ number_format($item->price_sale) }}
                      </td>
                    @if ( $item->image_1 != null)
                        <td class="text-center">
                            <img src="{{ asset('/products/' . $item->image_1) }}" alt="{{ $item->image_1 }}" style="width: 65px; height: auto" >
                        </td>
                    @endif
                    <td class="text-center text-right" style="font-size: 14px">
                      <a href="{{ route('product.edit', $item->id) }}" class="btn btn-info btn-sm">
                        <i class="fas fa-pencil-alt"></i>
                      </a>
                      @if (!empty($item->delete_id))
                        <form style="display:inline-block" action="{{ route('product.destroy', $item->id) }}" method="POST">
                          @method("DELETE")
                          @csrf
                          <button class="btn btn-danger"><i class="fas fa-trash"></i></button>
                        </form>
                      @endif
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        </div>
    </div>
@endsection

resources/views/admin/product/product-cmt.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
          <h3 class="card-title"> Product Comment</h3>
  
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 2%" class="text-center">
                          Id
                      </th>
                      <th style="width: 4%" class="text-center">
                        Customer 
                      </th>
                      <th style="width: 10%" class="text-center">
                        Product
                      </th>
                      <th style="width: 8%" class="text-center">
                        Content
                      </th>
                      {{-- <th style="width: 5%" class="text-center">
                        Actions
                      </th> --}}
                  </tr>
              </thead>
              <tbody>
                @foreach ($product_cmt as $item)
                  <tr>
                    <td class="text-center">
                      {{ $item->id }}
                  </td>
                  <td class="text-center">
                      {{ $item->Username->name ??'' }}
                  </td>
                    <td class="text-left">
                        {{ $item->Product->name }}
                    </td>
                    <td class="text-center">
                        {{ $item->content }}
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
    </div>
@endsection

resources/views/admin/product/product-img.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
          <h3 class="card-title"> Product Image</h3>
  
          <div class="card-tools">
            <a href="{{ route('product-img.create') }}" class="btn btn-tool">Add image</a>
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 2%" class="text-center">
                          Id
                      </th>
                      <th style="width: 10%" class="text-center">
                        Product Id
                      </th>
                      <th style="width: 5%" class="text-center">
                        Image
                      </th>
                      <th style="width: 3%" class="text-center">
                        Actions
                      </th>
                  </tr>
              </thead>
              <tbody>
                @foreach ($product_img as $item)
                  <tr>
                    <td class="text-center">
                      {{ $item->id }}
                  </td>
                    <td class="text-left">
                        {{ $item->Prod->name ??''}}
                    </td>
                    @if ( $item->image != null)
                        <td class="text-center">
                            <img src="{{ asset('/productImg/' . $item->image) }}" alt="{{ $item->image}}" style="width: 100px; height: auto" >
                        </td>
                    @endif
                    <td class="project-actions text-center">
                      <a href="{{ route('product-img.edit', $item->id) }}" class="btn btn-info btn-sm">
                        <i class="fas fa-pencil-alt"></i>
                      </a>
                      <form style="display:inline-block" action="{{ route('product-img.destroy', $item->id) }}" method="POST">
                        @method("DELETE")
                        @csrf
                        <button class="btn btn-danger"><i class="fas fa-trash"></i></button>
                      </form>
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        </div>
    </div>
@endsection