routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-session', function() {
    session()->forget('username');
    // return back();
});

Route::get('/','frontend\HomeController@index')->name('index');
Route::get('search','frontend\HomeController@search')->name('search');
//                         LOGIN                 //
Route::resource('login','frontend\LoginController');  //frontend
Route::post('logout','frontend\LoginController@logout')->name('logout');//frontend
Route::get('/admin/login','backend\HomeController@loginAdmin')->name('admin.login'); //backend
Route::post('process-login','backend\HomeController@processLogin')->name('process.login'); //backend
Route::post('admin-logout','backend\HomeController@logout')->name('admin.logout');//backend
///////////////////////////////////////////////////////////////////////////////////////////////////////
                //          frontend         //
Route::resource('user','frontend\UserController');
Route::get('/order-create','backend\OrderController@create')->name('order-create');
Route::post('/orders-store','backend\OrderController@store')->name('orders-store');
Route::get('/contactus','frontend\HomeController@contactus')->name('contactus');
Route::get('/detail','frontend\HomeController@detail')->name('detail');
Route::get('/checkout','frontend\HomeController@checkout')->name('checkout');
Route::get('/aboutus','frontend\HomeController@aboutus')->name('aboutus');
Route::get('/comic','frontend\HomeController@comic')->name('comic');
Route::get('/stationery','frontend\HomeController@stationery')->name('stationery');
Route::get('/magazine','frontend\HomeController@magazine')->name('magazine');
Route::get('/promotion','frontend\HomeController@promotion')->name('promotion');
Route::get('/book','frontend\HomeController@book')->name('book');
Route::get('/Faq','frontend\HomeController@Faq')->name('Faq');
Route::get('/my-account','frontend\MyAccountController@MyAccount')->name('my-account');
Route::get('/purchase','frontend\MyAccountController@purchase')->name('purchase');
Route::resource('product-img','backend\ProductImgController');
Route::resource('product-cmt','backend\ProductCmtController'); 
Route::resource('customer','frontend\UserController');
Route::get('/blog','frontend\HomeController@blog')->name('blog');
Route::get('/history','frontend\HomeController@history')->name('history');
Route::get('/history-detail/{id}','frontend\HomeController@histotyDeitail')->name('history-detail');
Route::resource('contact','frontend\ContactController');
//                       cart                       //
Route::get('/cart','frontend\CartController@cart')->name('cart');
Route::post('/add-cart','frontend\CartController@addcart')->name('add.cart');
Route::post('/delete-cart-item', 'frontend\CartController@deleteCartItem')->name('delete-cart-item');
Route::post('/delete-cart', 'frontend\CartController@deleteCart')->name('delete-cart');
Route::post('/chang-cart-quantity', 'frontend\CartController@changCartQuantity')->name('chang-cart-quantity');
/////////////////////////////////////////////////////////////////////////////////////////////////////
                 //          backend             //       
Route::group(['prefix' => 'admin',  'middleware' => 'admin'], function() {
    Route::get('/','backend\HomeController@dashboard')->name('dashboard');
    Route::get('/accountAdmin','backend\HomeController@adminIndex')->name('accountAdmin');
    Route::resource('account','backend\UserController');
    Route::resource('config','backend\ConfigController');
    Route::resource('sliders','backend\SliderController');
    Route::resource('product','backend\ProductController');
    Route::resource('orders','backend\OrderController');
    Route::resource('order-detail','backend\OrderDetailController');
    Route::get('order/{id}','backend\OrderController@orderDetail')->name('detail');
    Route::get('/detail-customer/{id}','backend\HomeController@detailCustomer')->name('detail-customer');
    Route::get('/detail/{id}','backend\HomeController@OrderDetail')->name('detail-order');
    Route::resource('blogadmin','backend\BlogController');
    Route::get('/contact','backend\HomeController@contact')->name('contact');
});
Route::get('{any}-{id}','frontend\HomeController@productDetails')->name('product-details');

resources/views/admin/account/account.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Customer</h3>
  
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 3%" class="text-center">
                          Id
                      </th>
                      <th style="width: 10%" class="text-center">
                          Name
                      </th>
                      <th style="width: 10%" class="text-center">
                          Email
                      </th>
                      <th style="width: 10%" class="text-center">
                          Phone
                      </th>
                      <th style="width: 10%" class="text-center">
                          Address
                      </th>
                      <th style="width: 10%" class="text-center">
                          Gender
                      </th>
                      <th style="width: 10%" class="text-center">
                          Status
                      </th>
                      <th style="width: 10%" class="text-center">
                          Roles
                      </th>
                      <th style="width: 10%" class="text-center">
                        Actions
                      </th>
                  </tr>
              </thead>
              <tbody>
                @foreach ($users as $item)
                    <tr>
                        <td class="text-center">
                            {{ $item->id??'' }}
                        </td>
                        <td class="text-center">
                            {{ $item->name }}
                        </td>
                        <td class="text-center">
                            {{ $item->email }}
                        </td>
                        <td class="text-center">
                            {{ $item->phone }}
                        </td>
                        <td class="text-center">
                            {{ $item->address }}
                        </td>
                        <td class="text-center">
                            {{ $item->gender }}
                        </td>
                        <td class="text-center">
                            {{ $item->status }}
                        </td>
                        <td class="text-center">
                            {{ $item->roles }}
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-info btn-sm" href="{{ route('detail-customer', $item->id) }}">
                                See detail
                            </a>
                            {{-- <a class="btn btn-danger btn-sm" href="#">
                                <i class="fas fa-trash">
                                </i>
                            </a> --}}
                        </td>
                    </tr>
                @endforeach
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
    </div>
@endsection
    

resources/views/admin/account/accountAdmin.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Admin</h3>
  
          <div class="card-tools">
            <a href="{{ route('account.create') }}" class="btn btn-tool">Create admin</a>
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 3%" class="text-center">
                          Id
                      </th>
                      <th style="width: 10%" class="text-center">
                          Name
                      </th>
                      <th style="width: 10%" class="text-center">
                          Email
                      </th>
                      <th style="width: 10%" class="text-center">
                          Phone
                      </th>
                      <th style="width: 10%" class="text-center">
                          Address
                      </th>
                      <th style="width: 10%" class="text-center">
                          Gender
                      </th>
                      {{-- <th style="width: 10%" class="text-center">
                          Status
                      </th> --}}
                      <th style="width: 10%" class="text-center">
                          Roles
                      </th>
                  </tr>
              </thead>
              <tbody>
                @foreach ($users as $item)
                  <tr>
                    <td class="text-center">
                        {{ $item->id }}
                    </td>
                    <td class="text-center">
                        {{ $item->name }}
                    </td>
                    <td class="text-center">
                        {{ $item->email }}
                    </td>
                    <td class="text-center">
                        {{ $item->phone }}
                    </td>
                    <td class="text-center">
                        {{ $item->address }}
                    </td>
                    <td class="text-center">
                        {{ $item->gender }}
                    </td>
                    {{-- <td class="text-center">
                        {{ $item->status }}
                    </td> --}}
                    <td class="text-center">
                        {{ $item->roles }}
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
    </div>
@endsection
    

resources/views/admin/account/createAdmin.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <div class="row">
        <div class="col-lg-11 col-sm-11 col-md-11 col-xs-11 bg-white ml-5">							
            <div class="card">
                <div class="card-body">
                    <div class="register-form form-item">
                        <form class="form-stl" action="{{ route('account.store') }}" name="frm-login" method="post"  >
                            @csrf
                            <div class="wrap-title">
                                <h3 class="form-title">Create Admin</h3>
                            </div>	
                            <div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Username</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="username" required placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Password</label>
                                    <input type="password" class="form-control" id="frm-reg-lname" min="6" name="password"required placeholder="*******">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Name</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="name"required placeholder="Name">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Gender</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="gender"  required placeholder="Gender">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Address</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="address"  required placeholder="Address">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Phone</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="phone" required placeholder="Phone">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Email</label>
                                    <input type="email" class="form-control" id="frm-reg-lname" name="email"  required placeholder="Email">
                                </div>
                                <div class="col-md-12" style="text-align: right">
                                    <input type="submit" class="btn btn-sign btn-primary" value="Create">
                                </div>
                            </div>
                        </form>
                    </div>											
                </div>
            </div><!--end main products area-->		
        </div>
    </div>
@endsection

resources/views/admin/account/detailCustomer.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Detail Customer</h3>
  
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card">
            <div class="card-body" style="padding-left:40px">
                <div class="row">
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Id: {{ $users->id }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Username: {{ $users->username }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Name: {{ $users->name }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Gender: {{ $users->gender }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Address: {{ $users->address }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Phone: {{ $users->phone }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Email: {{ $users->email }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Status: {{ $users->status }}</label>
                    </div>
                    <div class="wrap-input col-md-12">
                        <label for="frm-reg-lname">Roles: {{ $users->roles }}</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
    

resources/views/admin/account/editAdmin.blade.php
@extends('admin.layout.layout')
@section('title',$title ?? '')
@section('content')
    <div class="row">
        <div class="col-lg-11 col-sm-11 col-md-11 col-xs-11 bg-white ml-5">							
            <div class="card">
                <div class="card-body">
                    <div class="register-form form-item">
                        <form class="form-stl" action="{{ route('account.update', Auth::user()->id) }}" name="frm-login" method="post"  >
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="wrap-title">
                                <h3 class="form-title">Update Admin</h3>
                            </div>	
                            <div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Username</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="username" value="{{ $users->username ??''}}"required placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Name</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="name" value="{{ $users->name ??''}}" required placeholder="Name">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Gender</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="gender" value="{{ $users->gender ??''}}" required placeholder="Gender">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Address</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="address" value="{{ $users->address ??''}}" required placeholder="Address">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Phone</label>
                                    <input type="text" class="form-control" id="frm-reg-lname" name="phone" value="{{ $users->phone ??''}}" required placeholder="Phone">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Email</label>
                                    <input type="email" class="form-control" id="frm-reg-lname" name="email" value="{{ $users->email ??''}}" required placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <label for="frm-reg-lname">Roles</label>
                                    <select id="inputClientCompany" class="form-control"  name="roles" required class="form-control custom-select">
                                        <option selected disabled>{{ $users->roles  ??''}}</option>
                                            <option value="admin">admin</option>
                                    </select>
                                </div>
                                <div class="col-md-12" style="text-align: right">
                                    <input type="submit" class="btn btn-sign btn-primary" value="Update" name="register">
                                </div>
                            </div>
                        </form>
                    </div>											
                </div>
            </div><!--end main products area-->		
        </div>
    </div>
@endsection